[versions]
# androidX
appcompat = "1.6.1"
constraintLayout = "2.1.4"
dataBinding = "8.4.1"
ktx = "1.9.0"

glide = "4.16.0"

[libraries]
appcompact = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
dataBinding = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "dataBinding" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

[plugins]

[bundles]
androidx = ["core-ktx","appcompact","constraintLayout","dataBinding"]

